name: tiexpo
description: TIExpo — Textile Innovation Expo 2026 companion app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.0.0   # For storing auth tokens safely
  provider: ^6.1.1                 # For simple and effective state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
