name: tiexpo
description: TIExpo — Textile Innovation Expo 2026 companion app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.0.0   # For storing auth tokens safely
  provider: ^6.1.1                 # For simple and effective state management
  http: ^1.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.4 # Use the latest version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpeg" 
  color: "#ffffff" # Optional: specify a background color for the icon
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
